spring:
  application:
    name: att-gora-lista
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/todo_db}
    username: ${SPRING_DATASOURCE_USERNAME:todo_user}
    password: ${SPRING_DATASOURCE_PASSWORD:todo_password}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
